"""FakeInferenceAdapter — deterministic test double, no RNG."""

from __future__ import annotations

import hashlib
from datetime import timezone

from app.core.inference.domain.models import (
    ExecutionTrace,
    InferenceFinding,
    InferenceRequest,
    InferenceResult,
)
from app.core.inference.domain.enums import InferenceStatus
from app.core.inference.infrastructure import RUNTIME_VERSION


class FakeInferenceAdapter:
    """Deterministic adapter for tests — same input always yields same output."""

    @property
    def name(self) -> str:
        return "fake"

    @property
    def version(self) -> str:
        return "1.0.0"

    async def infer(self, request: InferenceRequest) -> InferenceResult:
        # Deterministic finding_key derived from product_key + session_id (no RNG).
        seed = f"{request.product_key}:{request.session_id}"
        finding_key = hashlib.sha256(seed.encode()).hexdigest()[:16]

        finding = InferenceFinding(
            artifact_type="clinical_finding",
            finding_key=finding_key,
            title=f"Fake finding for {request.product_key}",
            summary=f"Deterministic finding generated by FakeInferenceAdapter "
                    f"for session {request.session_id}.",
            confidence=0.9,
            attributes={"product_key": request.product_key, "session_id": request.session_id},
        )

        trace = ExecutionTrace(
            started_at=request.requested_at,
            finished_at=request.requested_at,
            adapter_name=self.name,
            adapter_version=self.version,
            runtime_version=RUNTIME_VERSION,
            product_key=request.product_key,
        )

        return InferenceResult(
            execution_id=request.execution_id,
            status=InferenceStatus.SUCCEEDED,
            findings=(finding,),
            execution_trace=trace,
            duration=0.0,
            runtime_metadata={},
        )
