"""add soap_note to summary

Revision ID: 5260ac1c03a9
Revises: 0001_initial_schema
Create Date: 2026-05-18 15:12:34.078792
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5260ac1c03a9'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('soap_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'soap_note')
    # ### end Alembic commands ###
